name: zavona_flutter_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  dartz: ^0.10.1
  flutter_svg: ^2.2.0
  go_router: ^16.2.0
  firebase_core: ^4.0.0
  firebase_crashlytics: ^5.0.0
  firebase_remote_config: ^6.0.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.0
  flutter_secure_storage: ^9.2.4
  http: ^1.5.0
  path_provider: ^2.1.5
  app_links: ^6.4.1
  google_fonts: ^6.3.0
  dev: ^1.0.0
  permission_handler: ^12.0.1
  image_picker: ^1.2.0
  geolocator: ^14.0.2
  fluttertoast: ^8.2.12
  google_sign_in: ^7.1.1
  sign_in_with_apple: ^7.0.1
  font_awesome_flutter: ^10.9.1
  animated_bottom_navigation_bar: ^1.4.0
  pinput: ^5.0.1
  easy_stepper: ^0.8.5+1
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  get_it: ^8.2.0
  geocoding: ^4.0.0
  google_maps_flutter: ^2.12.3
  google_places_flutter: ^2.1.1
  mime: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.4"
  build_runner: ^2.7.0
  freezed: ^3.2.0
  json_serializable: ^6.11.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/zavona_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/vectors/
    - assets/images/
