// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg5f51Pe4QzuhuKX55l1KA_7IRH-TFDmA',
    appId: '1:716348476419:web:a19b6e95eaee697a9b5236',
    messagingSenderId: '716348476419',
    projectId: 'zavona-92ffa',
    authDomain: 'zavona-92ffa.firebaseapp.com',
    storageBucket: 'zavona-92ffa.firebasestorage.app',
    measurementId: 'G-R2Z7ZXZYRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqxr5Tlq2uDK9JvQTWXnrKca5Pe2bJ05M',
    appId: '1:716348476419:android:5d142a67fcc2793f9b5236',
    messagingSenderId: '716348476419',
    projectId: 'zavona-92ffa',
    storageBucket: 'zavona-92ffa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-retpS95qFySFQHEdr9RuyHSNW5YUFl4',
    appId: '1:716348476419:ios:60d6b794dd60bd559b5236',
    messagingSenderId: '716348476419',
    projectId: 'zavona-92ffa',
    storageBucket: 'zavona-92ffa.firebasestorage.app',
    iosBundleId: 'in.zavona.zavonaParkingApp',
  );
}
